<?php

/**
 * Do not edit this file. Edit the config files in the config/ directory instead.
 *
 * It has to exist here because WordPress only looks for wp-config.php in its own
 * directory or one level up.
 */

require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';

require_once ABSPATH . 'wp-settings.php';
